-- -- Function to set colorscheme with pure black background
-- local function ColorMyPencils(color)
--   color = color or "tokyonight-night"
--   vim.cmd.colorscheme(color)
--
--   -- Set pure black background for Normal and NormalFloat
--   vim.api.nvim_set_hl(0, "Normal", { bg = "#000000" })
--   vim.api.nvim_set_hl(0, "NormalFloat", { bg = "#000000" })
-- end
--
-- return {
--   {
--     "folke/tokyonight.nvim",
--     lazy = false,
--     priority = 1000,
--     config = function()
--       require("tokyonight").setup({
--         style = "night", -- Darkest variant for pure black aesthetic
--         transparent = false, -- Disable transparent background
--         terminal_colors = true,
--         styles = {
--           comments = { italic = false }, -- Match your preference for non-italic comments
--           keywords = { italic = false }, -- Match your preference for non-italic keywords
--           functions = {},
--           variables = {},
--           sidebars = "dark",
--           floats = "dark",
--         },
--         -- Enforce pure black background
--         on_colors = function(colors)
--           colors.bg = "#000000"
--           colors.bg_dark = "#000000"
--           colors.bg_float = "#000000"
--           colors.bg_popup = "#000000"
--           colors.bg_sidebar = "#000000"
--           colors.bg_statusline = "#000000"
--         end,
--       })
--       ColorMyPencils() -- Call your function to apply colorscheme and set black background
--     end,
--   },
-- }


-- function ColorMyPencils(color)
-- 	color = color or "rose-pine"
-- 	vim.cmd.colorscheme(color)
--
-- 	vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
-- 	vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
--
-- end
--
-- return {
--     -- make this to be the same one as primeagen uses https://github.com/ThePrimeagen/neovimrc/blob/master/lua/theprimeagen/lazy/colors.lua i like to have the same as his
--     {
--         "folke/tokyonight.nvim",
--         config = function()
--             require("tokyonight").setup({
--                 -- your configuration comes here
--                 -- or leave it empty to use the default settings
--                 style = "night", -- The theme comes in three styles, `storm`, `moon`, a darker variant `night` and `day`
--                 transparent = true, -- Enable this to disable setting the background color
--                 terminal_colors = true, -- Configure the colors used when opening a `:terminal` in Neovim
--                 styles = {
--                     -- Style to be applied to different syntax groups
--                     -- Value is any valid attr-list value for `:help nvim_set_hl`
--                     comments = { italic = false },
--                     keywords = { italic = false },
--                     -- Background styles. Can be "dark", "transparent" or "normal"
--                     sidebars = "dark", -- style for sidebars, see below
--                     floats = "dark", -- style for floating windows
--                 },
--             })
--         end
--     },
--
--     {
--         "rose-pine/neovim",
--         name = "rose-pine",
--         config = function()
--             require('rose-pine').setup({
--                 disable_background = true,
--             })
--
--             vim.cmd("colorscheme rose-pine")
--
--             ColorMyPencils()
--         end
--     },
--
--
-- }

return {}
